source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'rake'
gem 'nokogiri'
gem 'activerecord'
gem 'jdbc-mysql'
gem 'pdf-reader'
gem 'browsermob-proxy'

#jdbc stuff
gem 'activerecord-jdbc-adapter'
gem 'jdbc-sqlite3'
gem 'activerecord-jdbcsqlite3-adapter'
gem 'jdbc-mysql'
gem 'activerecord-jdbcmysql-adapter', :platform => :jruby
gem 'capybara'



