source 'https://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'selenium-webdriver'
gem 'rake'
gem 'nokogiri'
gem 'activerecord'
gem 'jdbc-mysql'
gem 'activerecord-jdbcmysql-adapter'
gem 'pdf-reader'
gem 'browsermob-proxy'


